# {
    
#     "postTitle":"Updated Title",
#     "postBody":"Updated Body",
#     "imgUrl":"updated url",
#     "id":"7c374430-d05f-11ec-90d0-b9cafb0e6334",
#     "tags","udpated tags here"
    
# }

service: dynamodb-crud-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  environment:
    DYNAMO_TABLE_NAME: PostsTable
    region: us-west-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE_NAME}"
      # Resource: "arn:aws:dynamodb:#{AWS::region}:#{AWS::AccountId}:table/${self:provider.environment.DYNAMO_TABLE_NAME}"
      

  #     Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE_NAME}"
plugins:
  - "serverless-pseudo-parameters"
functions:
  listPosts:
    handler: post/list.listPosts
    events:
      - http:
          path: posts/list
          method: get
          cors: true

  createPost:
    handler: post/create.createPost
    events:
      - http:
          path: post/create
          method: post
          cors: true

  getPost:
    handler: post/get.getPost
    events:
      - http:
          path: post/{id}
          method: get
          cors: true

  updatePost:
    handler: post/update.updatePost
    events:
      - http:
          path: post/update
          method: patch
          cors: true

  deletePost:
    handler: post/delete.deletePost
    events:
      - http:
          path: post/delete
          method: delete
          cors: true

resources:
  Resources:
    UsersDynamoDbTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMO_TABLE_NAME}
